<?xml version="1.0" encoding="UTF-8"?>

<!-- Internal DTD  -->
<!DOCTYPE bookstore [
    <!ELEMENT bookstore (book+)>
    <!ELEMENT book (title, author+, year, price)>
    <!ATTLIST book category CDATA #REQUIRED>
    <!ATTLIST book cover CDATA #IMPLIED>
    
    <!ELEMENT title (#PCDATA)>
    <!ATTLIST title lang CDATA #REQUIRED>
    
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>

<bookstore>
    <book category="programming">
        <title lang="en">Java Complete Reference</title>
        <author>lan</author>
        <year>2015</year>
        <price>30.00</price>
    </book>
    <book category="programming">
        <title lang="en">C# Complete Reference</title>
        <author>balagurusamy</author>
        <year>2022</year>
        <price>29.99</price>
    </book>
    <book category="web">
        <title lang="en">XQuery Kick Start</title>
        <author>James McGovern</author>
        <author>Per Bothner</author>
        <author>Kurt Cagle</author>
        <author>James Linn</author>
        <author>Vaidyanathan Nagarajan</author>
        <year>2003</year>
        <price>49.99</price>
    </book>
    <book category="web" cover="paperback">
        <title lang="en">Learning XML</title>
        <author>Erik T. Ray</author>
        <year>2003</year>
        <price>39.95</price>
    </book>
</bookstore>
